name: model-training
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA }}

        run: |
          pip install -r requirements.txt
          dvc pull rossmann-store-sales/train_store.csv --run-cache
          dvc pull rossmann-store-sales/test.csv --run-cache
          cd models
          python RFR.py
          echo "## Random Forest Metric" >> report.md  
          cat rf_metrics.txt >> report.md

          cml-send-comment report.md
